### ISSUE TITLE
docstring example issue

### ISSUE THREAD

**Issue by thomasgas** [vuillaut/ctaplot#13]
this example is not up to date with the code (seems like):
https://github.com/vuillaut/ctaplot/blob/6d001ef0ba77ec48dec004313cc1da51183b57a1/ctaplot/plots.py#L554
Doint this change: ctaplot.ana.irf()  --> ctaplot.ana.irf_cta(), works for me.

**Comment by vuillaut** [comment]
Thanks. Solved.
