### ISSUE TITLE
curve comparison

### ISSUE THREAD

**Issue by thomasgas** [vuillaut/ctaplot#35]
What do you think about plotting the difference in percentage of a certain curve (ang res, en res, etc..) that my analysis have produces with respect to another curve (requirements, performances or some other curve)? I think it would be super useful.
maybe there's already a simple way of doing this but I haven't investigated it yet.
Thanks!!!

**Comment by vuillaut** [comment]
Hi

That would be useful yes.
There is nothing like that right now but it would be easy.
```
x_bin, res = ctaplot.ana.resolution_per_bin()
```
Apply operation to `res`
```
ctaplot.plots.plot_resolution(x_bin, res)
```

**Comment by vuillaut** [comment]
`plot_resolution_difference` introduced in #40 
Other cases are too specific and can be dealt with by user.

**Comment by thomasgas** [comment]
Thanks! ;)
